---
title: "generate_figures"
author: "Will Oestreich"
date: "10/16/2019"
output: github_document
---

Generate figures for comparison of marine and terrestrial dynamic management case studies.

```{r}
# Load necessary packages
library(tidyverse)
library(plyr)
library(reshape2)
library(gridExtra)
rm(list = ls())
```

# Data Preparation

Read in "cases" CSV file from literature review

```{r}
data<- read_csv("../data/cases.csv")  %>% 
  select(Domain, `Temporal scale (days)`, `Number of species`, `Spatial scale (km)`, Implementation, Year)
```


Data cleaning for subsequent analysis

```{r}
data$`Spatial scale (km)`[data$`Spatial scale (km)`=="Not explicitly defined"] <- NA
data$`Number of species`[data$`Number of species`=="Not explicitly defined"] <- NA
data$`Spatial scale (km)` <- as.numeric(data$`Spatial scale (km)`)
```


# Figures

## Figure 1 - timeline of case studies

```{r "figure_1", fig.width=4, fig.height=1.6, dpi=400 }
yearly_counts <- data.frame(Year = 1985:2019, Marine = numeric(35), Terrestrial = numeric(35))
for (i in 1985:2019) {
  yearly_counts$Marine[i-1984] <- sum(data$Year == i & data$Domain == "Marine")
  yearly_counts$Terrestrial[i-1984] <- sum(data$Year == i & data$Domain == "Terrestrial") 
}

Year = c((1985:2019),(1985:2019))
Count = c(yearly_counts$Marine,yearly_counts$Terrestrial)
Domain = c(rep("Marine",35),rep("Terrestrial",35))
df = data.frame(Year,Count,Domain)

ggplot(data = df, aes(x = Year, y = Count, color = Domain, fill = Domain, width = 0.75)) + 
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_continuous(breaks = seq(1985, 2015, by = 5)) +
  scale_colour_manual(values = c("Darkblue", "Chartreuse4")) +
  scale_fill_manual(values = c("Darkblue", "Chartreuse4")) +
  ylab("DM case studies") +
  ylim(0,8) +
  theme(panel.background = element_rect(fill = "white", colour = "white") ,panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
  theme(legend.position = c(0.15, 0.7))
```


## Figure 2 - spatial vs. temporal scale

```{r "figure_2",fig.width=4, fig.height=3.5, dpi=400 }
rm(Count, Domain, i, Year)

data<- data %>%
  select(Domain, `Temporal scale (days)`, `Spatial scale (km)`, Implementation, `Number of species`) %>%
  na.omit() 

data$`Temporal scale (days)` <- log10(data$`Temporal scale (days)`)
data$`Spatial scale (km)` <- log10(data$`Spatial scale (km)`)
data$`Number of species`[data$`Number of species` == 'Ecosystem'] <- '100'
data$`Number of species`[data$`Number of species` == '>100'] <- '100'
data$`Number of species` <- as.integer(data$`Number of species`)
data$`Number of species` <- log10(data$`Number of species`)

hull <- data %>%
  group_by(Domain) %>% 
  slice(chull(`Temporal scale (days)`, `Spatial scale (km)`))

data %>%
  ggplot(aes(`Temporal scale (days)`, `Spatial scale (km)`, colour = Domain, fill = Domain)) +
  scale_colour_manual(values = c("Darkblue", "Chartreuse4")) +
  scale_fill_manual(values = c("Darkblue", "Chartreuse4")) +
  geom_point(size = 4, alpha = 0.8, position = position_jitter(w = 0.01, h = 0)) +
  geom_polygon(data = hull, alpha=.5) +
  scale_x_continuous(breaks=c(0,1,2,3,4),
                     labels=c("1","10","100","1000","10000")) +
  scale_y_continuous(breaks=c(-2,-1,0,1,2,3),
                     labels=c("0.01","0.1","1","10","100","1000")) +  
  xlab(expression("Temporal scale (days)")) + 
  ylab(expression("Spatial scale (km)")) +
  theme(panel.background = element_rect(fill = "white", colour = "white"), panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
  theme(legend.position = c(0.85, 0.9))
```



## Figure 3 - Number of species vs. spatial scale, temporal scale

```{r "figure_3" , fig.width=14, fig.height=5, dpi=400}
# get_legend function from the following forum: 
# http://www.sthda.com/english/wiki/wiki.php?id_contents=7930
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

clabs <- c("1","10","Ecosystem-scale")
p1 <- data %>%
  ggplot(aes(`Temporal scale (days)`, `Number of species`, colour = Domain, fill = Domain)) +
  scale_colour_manual(values = c("Darkblue", "Chartreuse4")) +
  geom_point(size = 4, alpha = 0.8, position = position_jitter(w = 0.08, h = 0)) +
  xlab(expression("Temporal scale (days)")) + 
  ylab(expression("Number of species included")) +
  scale_x_continuous(breaks=c(0,1,2,3,4),
                     labels=c("1","10","100","1000","10000")) +
  scale_y_continuous(breaks = c(0,1,2),
                     labels = clabs) + 
  annotate("text", label = "(a)", x = 4.3, y = 2, size = 8, colour = "black") +
  theme(panel.background = element_rect(fill = "white", colour = "white"), panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

p2 <- data %>%
  select(Domain, `Spatial scale (km)`, `Number of species`, Implementation) %>%
  na.omit() %>%
  ggplot(aes(`Spatial scale (km)`, `Number of species`, colour = Domain, fill = Domain)) +
  scale_colour_manual(values = c("Darkblue", "Chartreuse4")) +
  geom_point(size = 4, alpha = 0.8, position = position_jitter(w = 0.08, h = 0)) +
  xlab(expression("Spatial scale (km)")) + 
  ylab("") +
  theme(legend.position = "none") +
  scale_x_continuous(breaks=c(-2,-1,0,1,2,3),
                     labels=c("0.01","0.1","1","10","100","1000")) +
  scale_y_continuous(breaks = c(0,1,2),
                     labels = clabs) + 
  annotate("text", label = "(b)", x = 3.3, y = 2, size = 8, colour = "black") +
  theme(panel.background = element_rect(fill = "white", colour = "white"), panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

legend <- get_legend(p1)

p1 <- p1 + theme(legend.position = "none")

grid.arrange(p1, p2, legend, ncol=3, widths=c(7, 7, 2))
```

